
server:
  port: 5000
  #servlet:
   # context-path: /api


#Datasource Configuaration
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
   
   
  datasource:
    url: jdbc:mysql://13.235.91.57:3306/crud_application
    username: root
    password: Nithin@143
    driver-class-name: com.mysql.cj.jdbc.Driver
 
jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY0MjcxODQ0OSwiaWF0IjoxNjQyNzE4NDQ5fQ.Oj1YAQjlkqm_Y5OWHNWc81gp2JyHKVIzNbbEr58l6xo   

#Logging
logging:
  pattern: 
    console: "%d{yyyy-mm-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    com:
      crudapplication: DEBUG
    org:
      springframework:
        jdbc:
          core: TRACE
       # boot: DEBUG
  file: 
    path: ./
    name: crudapp.log
        
  
  
  
  
  
  
  
  
  
  
  
  



